config/routes.rb
Rails.application.routes.draw do


  root 'subforums#index'

  get '/subforums' => 'subforums#index'
  get '/subforums/new' => 'subforums#new'
  post '/subforums'=>'subforums#create'
  get '/subforums/:id' => 'subforums#show', :as=>'subforum'
  get '/subforums/:id/edit' => 'subforums#edit',:as=>'edit_subforum'
  patch '/subforums/:id' => 'subforums#update'
  delete '/subforums/:id' => 'subforums#destroy'

  get '/topics' => 'topics#index', :as=>'topic_index'
  get '/topics/new' => 'topics#new'
  post '/topics/:subforum_id'=>'topics#create'
  get '/topics/:id' => 'topics#show', :as=>'topic'
  delete '/topics/:id' => 'topics#destroy'
  get '/topics/:id/edit' => 'topics#edit',:as=>'edit'
  patch '/topics/:id' => 'topics#update'

  post '/comments/:topic_id'=>'comments#create', :as=>'comments'
  get '/comments/:id/edit' => 'comments#edit',:as=>'edit_comment'
  patch '/comments/:id' => 'comments#update'

  get '/tags' => 'tags#index', :as=>'tag_index'
  get '/tags/:id' => 'tags#show', :as=>'tag'
  post '/tags/:topic_id'=>'tags#create'

  get '/signup'=> 'users#new'
  post '/users'=> 'users#create'
  get '/users/:id'=> 'users#show', as: :user

  get '/login'=> 'sessions#new'
  post '/sessions'=> 'sessions#create'
  get '/logout'=> 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic

  validates :topic_id, :allow_nil=>false,:presence=>true
  validates :user, :allow_nil=>false,:presence=>true
  validates :post_number, :presence=>true
  validates :content, :allow_nil=>false, :presence=>true
end

app/models/connector.rb
class Connector < ActiveRecord::Base
  belongs_to :topic
  belongs_to :tag

  validates :tag_id, :allow_nil=>false, :presence=>true
  validates :topic_id, :allow_nil=>false, :presence=>true
end

app/models/subforum.rb
class Subforum < ActiveRecord::Base
  has_many :topics

  validates :title, :uniqueness =>true, :allow_nil=>false,:presence=>true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :connectors
  has_many :topics, :through => :connectors

  validates :title, :uniqueness =>true, :allow_nil=>false,:presence=>true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments
  has_many :connectors
  has_many :tags, :through => :connectors
  belongs_to :subforum

  validates :title, :allow_nil=>false,:presence=>true
  validates :subforum_id, :presence=>true
  validates :content, :allow_nil=>false,:presence=>true

end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password

  validates :username, :uniqueness => true, :allow_nil => false, :presence => true
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    com=Comment.new
    com.topic_id = params["topic_id"]
    com.user=User.find_by(id: session["user_id"]).username
    com.post_number=params["id"].to_i
    com.content=params["content"]
    com.save
    redirect_to topic_url(com.topic_id)
  end

  def edit
    @comment= Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update content: params[:content]

    redirect_to topic_url(@comment.topic_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Goodbye"
  end

  def create
    user=User.find_by(username: params[:username])
    if user
      if user.authenticate(params[:password])
        session["user_id"]=user.id
        redirect_to root_url, notice: "Welcome back"
      else
        redirect_to root_url, notice: "Unknown username or password"
      end
    else
      redirect_to root_url, notice: "Unknown username or password"
    end
  end
end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController

  def index
    @subforums = Subforum.all.limit(1000)
  end

  def show
    @subforum = Subforum.find(params[:id])
  end

  def new
  end

  def create
    Subforum.create title: params[:title]

    redirect_to root_path
  end

  def edit
    @subforum = Subforum.find(params[:id])
  end

  def update
    @subforum = Subforum.find(params[:id])
    @subforum.update title: params[:title]

    redirect_to subforum_url(@subforum.id)
  end

  def destroy
    Subforum.delete(params[:id])

    redirect_to root_path
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all.limit(1000)
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create
    Tag.create title: params[:title] #will only happen if doesnt exist already
    @tag = Tag.find_by(title: params[:title])

    con=Connector.new
    con.topic_id = params["topic_id"]
    con.tag_id = @tag.id
    if !Connector.exists?(topic_id: params["topic_id"], tag_id: @tag.id)
      con.save #only save if it doesnt exist already, otherwise just use it for redirect
    end
    redirect_to topic_url(con.topic_id)
  end

  def destroy
    @connector= Connector.find(params[:id])
    Connector.delete(params[:id])
    redirect_to topic_url(@connector.topic_id)
  end
  end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all.limit(1000)
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
  end

  def create
    top=Topic.new
    top.subforum_id = params["subforum_id"]
    top.content=params["content"]
    top.title=params["title"]
    top.user=User.find_by(id: session["user_id"]).username
    top.save
    redirect_to subforum_url(top.subforum_id)
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update title: params[:title],
        content: params[:content]

    redirect_to topic_url(@topic.id)
  end

  def destroy
    @topic= Topic.find(params[:id])
    Topic.delete(params[:id])
    redirect_to subforum_url(@topic.subforum_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]

  def new
    @user=User.new
  end

  def authorize
    @user=User.find_by(id: params[:id])
    if @user.blank? || session[:user_id]!=@user.id
      redirect_to root_url, notice: "Can't be blank"
    end
  end

  def show

  end

  def create
    @user=User.new(username: params[:username], password: params[:password])
    if @user.save
      redirect_to root_url, notice: "You are registered"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h2>Edit your comment</h2>

<%=form_tag comments_url(@comment.id),:method=>'patch' do%>
    <p><label>Content:</label></p><textarea name="content" cols="80" rows="3"><%=@comment.content%></textarea>
    <p><button>Submit</button></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "pull-right">
    <h1><%= link_to "White Sox Forum", "/" %>
   <% Subforum.all.limit(20).each do |subforum| %>
            <small>  <%= link_to subforum.title, subforum_url(subforum.id), :method=> 'get' %></small>
           <% end %>
        <small>  <%= link_to "Tags", tag_index_url, :method=> 'get' %></small>
    </h1>
    <% if session["user_id"].present?%>
        Hi, <%= User.find_by(id: session["user_id"]).username %>
        <%= link_to "My Account", user_path(User.find_by(id: session["user_id"])) %>
        <%= link_to "Sign Out", '/logout'%>
            <%else%>
    <%= link_to "Sign Up", '/signup' %>
        <%=link_to "Sign In", '/login'%>
        <% end%>

</div>

<%if notice.present?%>
<div class="alert alert-info">
    <%=notice%>
    </div>
<%end%>



<%= yield %>

</body>
</html>

app/views/subforums/edit.html.erb
<% if session[:user_id].present? %>
    <%if User.find_by(id: session["user_id"]).username == "Admin"%>
<h2>Edit The Subforum</h2>

<%=form_tag subforum_url(@subforum.id),:method=>'patch' do%>
    <p><label>Title:</label> <input name="title" size="30" value="<%=@subforum.title%>"></p>
    <p><button>Submit</button></p>
        <%end%>
    <%end%>
    <%end%>

app/views/subforums/index.html.erb
<% if session[:user_id].present? %>
    <%if User.find_by(id: session["user_id"]).username == "Admin"%>
        <p><%= link_to "Create a Subforum", subforums_new_url %></p>
    <% end %>
<% end %>
<ul>

  <% @subforums.each do |subforum| %>
    <li>
      <%= link_to subforum.title, subforum_url(subforum.id), :method=> 'get' %>
      <% if session[:user_id].present? %>
        <%if User.find_by(id: session["user_id"]).username == "Admin"%>
            <%= link_to "(delete)", subforum_url(subforum.id), :method=> 'delete' %>
        <% end %>
      <% end %>
    </li>
  <% end %>
    <li><%= link_to "Topic Index", topic_index_url, :method=> 'get' %></li>

</ul>

app/views/subforums/new.html.erb
<% if session[:user_id].present? %>
    <%if User.find_by(id: session["user_id"]).username == "Admin"%>
<h2>Create a Subforum</h2>

<%=form_tag "/subforums", :method => 'post' do%>
    <p><label>Title:</label> <input name="title" size="30"></p>
    <p><button>Submit</button></p>
    <% end %>
    <% end %>
<% end %>

app/views/subforums/show.html.erb
<%= link_to "Go Back", "/"%>
<h2><%= @subforum.title %></h2>

<p>
    <% if session["user_id"].present?%>
        <%if User.find_by(id: session["user_id"]).username == "Admin"%>
            <%= link_to "Edit", edit_subforum_url(@subforum.id) %>
        <%end%>
    <%end%>
</p>


<ul>



<% Topic.where(subforum_id: @subforum.id).each do |topic| %>
    <li>
        <%= link_to topic.title, topic_url(topic.id), :method=> 'get' %>
        <% if session["user_id"].present?%>
            <%if User.find_by(id: session["user_id"]).username == topic.user%>
                <%= link_to "(delete)", topic_url(topic.id), :method=> 'delete' %>
            <%end%>
        <%end%>
    </li>
<% end %>

</ul>
<br>
<br>
<br>
<br>

<% if session["user_id"].present?%>
<h3>Add a New Topic</h3>

<%=form_tag topic_url(@subforum.id), :method => 'post' do%>
    <p><label>Title:</label> <input name="title" size="30"></p>
    <p><label>Content:</label></p><textarea name="content" cols="80" rows="3"></textarea>
    <p><button>Submit</button></p>
<% end %>
<% end %>

app/views/tags/index.html.erb
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.title, tag_url(tag.id), :method=> 'get' %>
    </li>
  <% end %>

app/views/tags/show.html.erb
<h2><%= @tag.title %></h2>


<ul>

    <% @tag.topics.each do |t| %>
        <li><%=link_to t.title, topic_url(t.id), :method=> 'get' %></li>
    <%end%>
</ul>

app/views/topics/edit.html.erb
<% if session["user_id"].present?%>
    <%if User.find_by(id: session["user_id"]).username == @topic.user%>
<h2>Edit Your Topic</h2>

<%=form_tag topic_url(@topic.id),:method=>'patch' do%>
    <p><label>Title:</label> <input name="title" size="30" value="<%=@topic.title%>"></p>
    <p><label>Content:</label></p><textarea name="content" cols="80" rows="3"><%=@topic.content%></textarea>
    <p><button>Submit</button></p>
    <% end %>
    <% end %>
<% end %>

app/views/topics/index.html.erb
<h2>Topic Index</h2>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.title, topic_url(topic.id), :method=> 'get' %>
        <% if session["user_id"].present?%>
            <%if User.find_by(id: session["user_id"]).username == topic.user%>
                 <%= link_to "(delete)", topic_url(topic.id), :method=> 'delete' %>
            <% end %>
        <% end %>
    </li>
  <% end %>

</ul>

app/views/topics/new.html.erb
<% if session["user_id"].present?%>
<h2>Add a New Topic</h2>

<%=form_tag "/topics", :method => 'post' do%>
  <p><label>Title:</label> <input name="title" size="30"></p>
  <p><label>Content:</label></p><textarea name="content" cols="80" rows="3"></textarea>
  <p><button>Submit</button></p>
    <% end %>
<% end %>

app/views/topics/show.html.erb
<% if Subforum.exists?(@topic.subforum_id)%>
    <%= link_to "Go Back", subforum_url(@topic.subforum_id)%>
    <%else%>
    <%= link_to "Go Back", topic_index_url%>
<%end%>


<h2><%= @topic.title %></h2>
<% @topic.tags.each do |t| %>
    <%=link_to t.title, tag_url(t.id) %>,
<%end%>


<div>
    <p><hr><br><b><i>User: <%= @topic.user%></i></b>
    <br>
    <br>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= @topic.content %>
    </p>

    <p>
        <% if session["user_id"].present?%>
            <%if User.find_by(id: session["user_id"]).username == @topic.user%>
        <%= link_to "Edit", edit_url(@topic.id) %>
                <% end %>
        <% end %>

    </p>


    <% Comment.where(topic_id: @topic.id).each do |comment| %>
        <p><hr><br><b><i>User: <%= comment.user%></i></b>
        <br>
        <br>
        &nbsp&nbsp&nbsp&nbsp&nbsp<%= comment.content %>
        <p><% if session["user_id"].present?%>
            <%if User.find_by(id: session["user_id"]).username == comment.user%>
                <%= link_to "Edit", edit_comment_url(comment.id) %>
                    </p>
            <% end %>
        <% end %>
        </p>
        </div>
    <% end%>
    <% if session["user_id"].present?%>
    <h3>Reply:</h3>
    <%=form_tag comments_url(@topic.id) do%>
        <p>Content:<br> <textarea name="content" rows="5"cols="100"></textarea></p>
        <p><input type="submit" value="Send"></p>
    </form>
    <% end%>

        <h3>Tag this thread:</h3>
        <%=form_tag tag_url(@topic.id) do%>
            <p><label>Tag:</label> <input name="title" size="30"></p>
            <p><button>Submit</button></p>
        <% end %>

<% end%>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<% if @user.errors.any? %>
    <ul class="errors">
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_tag "/users" do %>
    <p>
        <%=label_tag :username%>
        <%=text_field_tag :username%>
    </p>
    <p>
        <%= label_tag :password %>
        <%= text_field_tag :password %>
    </p>
    <%= submit_tag "submit" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<p>
    <strong>Username:</strong> <%= @user.username %>
    <strong>Password:</strong> <%= @user.password %>
</p>